{% set python_min = "3.12" %}
{% set name = "nmma" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nmma-{{ version }}.tar.gz
  sha256: a6dd84e2c74ae3a5efbf1fd89a1dbde0070040148fea7bf41ae8dda805af57d9

build:
  entry_points:
    - nmma-generation=nmma.pbilby.generation:main_nmma
    - nmma-gw-generation=nmma.pbilby.generation:main_nmma_gw
    - nmma-analysis=nmma.pbilby.analysis:main_nmma
    - nmma-gw-analysis=nmma.pbilby.analysis:main_nmma_gw
    - lightcurve-analysis=nmma.em.analysis:main
    - lightcurve-analysis-lbol=nmma.em.analysis_lbol:main
    - lightcurve-analysis-condor=nmma.em.analysis_condor:main
    - lightcurve-injection-summary=nmma.em.injection_summary:main
    - lightcurve-injection-slurm-setup=nmma.em.create_injection_slurm:main
    - lightcurve-injection-condor-setup=nmma.em.create_injection_condor:main
    - lightcurve-manual=nmma.em.manual:main
    - lightcurve-marginalization=nmma.em.lightcurve_marginalization:main
    - combine-EOS=nmma.em.combine_EOS:main
    - create-lightcurve-slurm=nmma.em.create_lightcurves_slurm:main
    - create-lightcurve-condor=nmma.em.create_lightcurves_condor:main
    - create-svdmodel=nmma.em.create_svdmodel:main
    - svdmodel-benchmark=nmma.em.svdmodel_benchmark:main
    - svdmodel-download=nmma.utils.models:main
    - lightcurve-generation=nmma.em.create_lightcurves:main
    - lightcurve-detection=nmma.em.detect_lightcurves:main
    - nmma-create-injection=nmma.eos.create_injection:main
    - gwem-resampling=nmma.em.gwem_resampling:main
    - gwem-resampling-condor=nmma.em.gwem_resampling_condor:main
    - gwem-Hubble-estimate=nmma.em.gwem_Hubble_estimate:main
    - convert-skyportal-lcs=tools.convert_skyportal_lcs:main
    - resample-grid=tools.resample_grid:main

  script: |
    {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - arviz
    - astropy-base >=5.3.4
    - bilby >=2.4.1
    - bilby_pipe ==1.5.0
    - colorcet
    - corner
    - dust_extinction
    - dynesty
    - future
    - gwpy
    - healpy
    - h5py
    - joblib
    - lal
    - lalsimulation
    - ligo.skymap
    - ligo-followup-advocate
    - matplotlib-base >3.8
    - mpi4py
    - nestcheck
    - notebook
    - numpy >2.0
    - pandas >2.0
    - parallel-bilby
    - p-tqdm
    - pymultinest
    - python >={{ python_min }}
    - pyyaml
    - requests
    - scikit-learn >=1.0.2
    - scipy >=1.10
    - seaborn
    - sncosmo
    - tensorflow
    - tornado
    - tqdm
    - ultranest
    - multiprocess <=0.70.16

test:
  imports:
    - nmma
  commands:
    - pip check
    # - lightcurve-analysis --help skip this time
    - lightcurve-injection-summary --help
    - lightcurve-injection-slurm-setup --help
    - lightcurve-injection-condor-setup --help
    - lightcurve-marginalization --help
    - combine-EOS --help
    - create-lightcurve-slurm --help
    - create-lightcurve-condor --help
    - create-svdmodel --help
    - lightcurve-generation --help
    - lightcurve-detection --help
    - nmma-create-injection --help
    - gwem-resampling --help
    - gwem-resampling-condor --help
    - gwem-Hubble-estimate --help
    - lightcurve-analysis-condor --help
  requires:
    - pip
    - mpi4py
    - nestcheck
    - python {{ python_min }}

about:
  home: https://github.com/nuclear-multimessenger-astronomy/nmma
  summary: A nuclear physics multi-messenger Bayesian inference library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sahiljhawar
    - mcoughlin
